### PR TITLE
Backport patches related to password prompt

### PR DESCRIPTION
**Pull request by marmarek**
Backport:
- https://gitlab.freedesktop.org/plymouth/plymouth/-/commit/b41e40e065c60e76b9721747492875c3454440dc
(merged upstream)
- https://gitlab.freedesktop.org/plymouth/plymouth/-/merge_requests/166
  (not yet merged)

QubesOS/qubes-issues#2199
QubesOS/qubes-issues#5521

### CODE REVIEW

**Comment by marmarek** [comment]
FYI @mati7337

**Comment by marmarek** [comment]
PipelineRetry

**Comment by marmarek** [comment]
PipelineRetry

**Comment by marmarek** [comment]
PipelineRefresh

**Comment by fepitre** [comment]
PipelineRefresh

**Comment by fepitre** [comment]
PipelineRetry

**Comment by fepitre** [comment]
PipelineRetry

**Comment by fepitre** [comment]
PipelineRefresh

**Comment by fepitre** [comment]
PipelineRefresh

**Comment by marmarek** [comment]
PipelineRefresh

**Pull request merged**
